services:
  api:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    environment:
      DATABASE_URL: postgresql+psycopg://integrationops:integrationops@postgres:5432/integrationops
      TASK_MODE: celery
      SCHEDULER_ENABLED: "false"
      REDIS_URL: redis://redis:6379/0
      CORS_ORIGINS: http://localhost:3000
    ports: ["8000:8000"]
    depends_on: [postgres, redis]

  worker:
    build: .
    command: celery -A app.celery_app.celery_app worker --loglevel=INFO
    environment:
      DATABASE_URL: postgresql+psycopg://integrationops:integrationops@postgres:5432/integrationops
      TASK_MODE: celery
      REDIS_URL: redis://redis:6379/0
    depends_on: [postgres, redis]

  beat:
    build: .
    command: celery -A app.celery_app.celery_app beat --loglevel=INFO
    environment:
      DATABASE_URL: postgresql+psycopg://integrationops:integrationops@postgres:5432/integrationops
      TASK_MODE: celery
      REDIS_URL: redis://redis:6379/0
    depends_on: [postgres, redis]

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: integrationops
      POSTGRES_USER: integrationops
      POSTGRES_PASSWORD: integrationops
    volumes: ["postgres_data:/var/lib/postgresql/data"]

  redis:
    image: redis:7-alpine

  prometheus:
    image: prom/prometheus:latest
    command: ["--config.file=/etc/prometheus/prometheus.yml"]
    volumes:
      - ./observability/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports: ["9090:9090"]
    depends_on: [api]

  grafana:
    image: grafana/grafana:latest
    ports: ["3001:3000"]
    volumes:
      - ./observability/grafana/provisioning:/etc/grafana/provisioning:ro
    depends_on: [prometheus]

volumes:
  postgres_data:
